version: '3.8'
services:
  web:
    build: .
    env_file: .env
    ports:
      - '8000:8000'
    depends_on:
      - redis
    command: daphne -b 0.0.0.0 -p 8000 project_name.asgi:application
  redis:
    image: redis:7
    ports:
      - '6379:6379'
